# Generated by Django 2.0.4 on 2018-04-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='comment',
        ),
    ]
