# Generated by Django 2.0.4 on 2018-04-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analytics',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='link',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitedetail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.AddField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='comment_thumbnail/%Y/%m/%d/', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='file',
            name='src',
            field=models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(help_text='送信後、一度保存してください。', upload_to='images/%Y/%m/%d/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnail/%Y/%m/%d/', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='recomment_thumbnail/%Y/%m/%d//', verbose_name='サムネイル'),
        ),
    ]
