# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='com_icon/', verbose_name='アイコン'),
        ),
    ]
