# Generated by Django 2.0.4 on 2018-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedetail',
            name='description',
            field=models.TextField(default='サンプルの説明', max_length=255, verbose_name='サイトの説明'),
        ),
    ]
