# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_recomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('page_view', models.IntegerField(verbose_name='ページビュー数')),
            ],
        ),
    ]
