# Generated by Django 2.0.3 on 2018-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180310_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetail',
            name='header_text',
            field=models.TextField(default='このブログはDjangoとBootstrap4で作成されました\n[filter url]https://github.com/naritotakizawa/django-torina-blog<split>Githubのソースコード', max_length=255, verbose_name='ヘッダーのテキスト'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(help_text='送信後、一度保存してください。', upload_to='uploads/%Y/%m/%d/', verbose_name='画像'),
        ),
    ]
