# Generated by Django 2.0.4 on 2018-04-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_file_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='file_comment', to='blog.Comment', verbose_name='コメント'),
        ),
    ]
