# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170323_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='target',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
