# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_html',
        ),
    ]
