# Generated by Django 2.0.4 on 2018-04-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180415_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='recomment',
            name='file',
        ),
    ]
