# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170518_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='概要'),
        ),
    ]
