# Generated by Django 2.0.4 on 2018-04-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180415_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='src',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='添付ファイル'),
        ),
    ]
